# This is a basic workflow to help you get started with Actions
name: Most used (with details)

# Controls when the workflow will run
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_skipped: >-
                weefy, colab-notebooks, taeyang_rint, crelated-archives, supreme-octo-carnival
          plugin_languages_ignored: >-
                jupyter notebook, html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
                gnuplot
          plugin_languages_details: percentage
          plugin_languages_limit: 4
          #config_display: large
